# Generated by Django 4.1.7 on 2023-03-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=65, verbose_name='name')),
                ('broker', models.CharField(max_length=65)),
                ('account', models.IntegerField()),
                ('exp_date', models.DateField()),
            ],
        ),
    ]
