# Generated by Django 4.1.7 on 2023-03-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algotrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=65)),
                ('slug', models.SlugField(unique=True)),
                ('platform', models.CharField(max_length=65)),
                ('market', models.CharField(max_length=65)),
                ('account_type', models.CharField(max_length=65)),
                ('stoploss', models.CharField(max_length=250)),
                ('gain', models.CharField(max_length=65)),
                ('volume', models.CharField(max_length=65)),
                ('time', models.CharField(max_length=65)),
                ('indicators', models.CharField(max_length=165)),
                ('timeframe', models.CharField(max_length=65)),
                ('security', models.CharField(max_length=65)),
                ('magic', models.CharField(max_length=65)),
                ('comment', models.CharField(max_length=65)),
                ('order_type', models.CharField(max_length=65)),
                ('trailing', models.CharField(max_length=65)),
                ('goals', models.CharField(max_length=65)),
                ('functionality', models.CharField(max_length=500)),
            ],
        ),
    ]
